apiVersion: apps/v1
kind: Deployment
metadata:
  name: onlinebookstore
spec:
  selector:
    matchLabels:
      app: onlinebookstore
  replicas: 2
  template:
    metadata:
      labels:
        app: onlinebookstore
    spec:
      containers:
        - name: onlinebookstore
          image: mvmadhan/tomcat:8
          ports:
            - containerPort: 8080
          env:   # Setting Enviornmental Variables
            - name: DB_HOST   # Setting Database host address from configMap
              valueFrom :
                configMapKeyRef :
                  name : db-config
                  key :  host

            - name: DB_NAME  # Setting Database name from configMap
              valueFrom :
                configMapKeyRef :
                  name : db-config
                  key :  dbName

            - name: DB_USERNAME  # Setting Database username from Secret
              valueFrom :
                secretKeyRef :
                  name : mysql-secrets
                  key :  username

            - name: DB_PASSWORD # Setting Database password from Secret
              valueFrom :
                secretKeyRef :
                  name : mysql-secrets
                  key :  password

---

apiVersion: v1
kind: Service
metadata:
  name: onlinebookstore-svc
spec:
  type: NodePort
  ports:
  - name: http
    port: 80
    targetPort: 8080
    protocol: TCP
  selector:
    app: onlinebookstore

