
apiVersion: apps/v1
kind: Deployment
metadata:
  name: onlinebookstore
  labels:
    app: onlinebookstore
spec:
  replicas: 2
  selector:
    matchLabels:
      app: onlinebookstore
  template:
    metadata:
      labels:
        app: onlinebookstore
    spec:
      containers:
      - name: onlinebookstore
        image: mvmadhan/tomcat:17
        ports:
        - containerPort: 8080
